### ISSUE TITLE
Phasechange : ne fonctionne que pour glacer l'eau

### ISSUE THREAD

**Issue by Zohnat** [Avatar-Realms/spigot-bending#107]
Salut!

Je voulais juste signaler qu'un water ne peut pas phasechange les boules de glaces engendrées par Surge ou Torrent.

Un heatcontrol peut cependant faire fondre ces boules.

**Comment by Koudja** [comment]
Résolu: e4bf5dbfb8d0bef36fe23b3c88bbbdd0a8cba355
