### ISSUE TITLE
Octopusform : fonctionnalité disparue

### ISSUE THREAD

**Issue by Zohnat** [Avatar-Realms/spigot-bending#108]
Salut!

Avant, l'octopusform, si l'on se jetait dans l'eau avec, permettait de générer une quantité de glace incroyable autour du lanceur, lui permettant d'être relativement safe.

Apparemment ça ne marche plus.

**Comment by Koudja** [comment]
L'OctopusForm ayant reçu un rework pour sa version glace, je clos ce ticket.
