### ISSUE TITLE
Poisondart + Parastick marche pas.

### ISSUE THREAD

**Issue by Shuboh** [Avatar-Realms/spigot-bending#109]
Le poisondart buff avec le parastick ne marche pas le buff donné par le parastick (provoquant une perte de son bending pendant 2sec.) ne s'active pas

**Comment by ghost** [comment]
Hello !
Dans blockChi() de EntityTools ligne 165, il ne faudrait pas mettre 

``` java
blockedChis.put(player, time+System.currentTimeMillis());
```

Au passage, dans la news du 22 juillet, ce combo est marqué comme censé stopper le bending pendant 2s or l'attribut PARASTICK_CHIBLOCK_DURATION est de 3000ms .

**Comment by Koudja** [comment]
Les valeurs présentes dans le code ne sont utilisées que par défaut (absence de fichier de configuration), sur le serveur nous en avons un.

**Comment by ghost** [comment]
Ah oui pardon j'avais oublié le fichier de configuration, je me base souvent sur les temps écrits ici alors que je ne devrais pas.

**Comment by Koudja** [comment]
Résolu: 70809e60dd378b1bdaee7c1147fc7e7e1c1a0cb5
