### ISSUE TITLE
Surge

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#11]
Bonsoir !
Aujourd'hui je me risque à un autre bend que le mien :3
Le surge a quelques problème : quand on utilise le WaterWall, et qu'ensuite on veut placer une balise avec le sneak pour envoyer la Wave, le Wall revient immédiatement, comme si il n'avait jamais disparu. Un des moyens de "l’arrêter" est de se déconnecter.
J'ai remarqué que WaterWall.java ne possédait pas de fonction canTick(). J'ai essayé d'en faire une :

``` java
@Override
    public boolean canTick()
    {
        if(!super.canTick())
        {
            return false;
        }
        if (!getState().equals(BendingAbilityState.PROGRESSING) && !NAME.equals(bender.getAbility()))
        {
            return false;
        }
        if (getState().equals(BendingAbilityState.PROGRESSING) && wave == null && !this.player.isSneaking())
        {
            return false;
        }
        return true;
    }
```

J'espère que ça vous aidera !

**Comment by Koudja** [comment]
Voir : 832c0fe48130a6830ae5b3f80bcc4ceeb5c07a64
Le problème venait du fait qu'en cas de "non sneak" (check dans la méthode progress), "returnWater" était appelé. A cause au fonctionnement de celui-ci, la coméptence n'est pas considéré comme "arrêtée" directement, mais unqiue lorsque WaterReturn le seras. le problème est que le code était commenté (artefact).
