### ISSUE TITLE
Earthblast et watermanip bug

### ISSUE THREAD

**Issue by Shuboh** [Avatar-Realms/spigot-bending#110]
En mettant le plugin sur un serveur en local host rapidement, j'ai rencontré de gros probleme avec les bend a source.
http://image.noelshack.com/fichiers/2016/30/1469748529-2016-07-29-01-24-53.png
http://image.noelshack.com/fichiers/2016/30/1469748529-2016-07-29-01-26-38.png
les image ci dessus montre les effets des sort watermanipulation et earthblast, l'un laisse une source d'eau indefiniment la ou elle touche et l'autre créer un chemin de pierre la ou je vise

Je ne sais pas a quoi c'est du les logs de mon serveur ne montre rien.
Je ne sais pas non plus si cela viens du serveur en lui meme j'ai use le spigot de votre pack.

**Comment by ghost** [comment]
Salut ! Je pense que ce problème provient très certainement de ton serveur, sachant que ce bug n'est ni présent sur Bendercraft, ni sur un serveur créatif que je possède ^^ Si tu n'as pas de logs particulier, essaye de construire la dernière version de spigot [via leur buildtool](https://www.spigotmc.org/wiki/buildtools/).

**Comment by Koudja** [comment]
Bonjour, le spigot fournit dans le bending n'est pas à jour (autre que l'API). Je vous conseille de télécharger/construire une fraiche version de celui-ci.

Quant au problème énoncé, je regrette mais je ne fournirais pas de support dans la mesure où le problème n'est pas reproductible (j'utilise moi-même un serveur en localhost sans aucun soucis).

Si vous avez un moyen de reproduire le problème à 100%, je vous prierais de ré-ouvrir ce ticket.
