### ISSUE TITLE
FireBurst ne se réinitialise pas correctement

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#111]
Bonjour !
Si l'on charge un FireBurst, que l'on arrête de sneaker, puis que l'on reprend, le chargement ne s'est pas réinitialisé, et reprend là ou il s'était arrêté. 
Peut-être pourrait-on changer la fonction canTick() du FireBurst actuel en reprenant celle de l'Airburst :

``` java
@Override
    public boolean canTick() {
        if(!super.canTick()) {
            return false;
        }
        if(getState().equals(BendingAbilityState.PREPARING) && !this.player.isSneaking()) {
            return false;
        }
        if (!getState().equals(BendingAbilityState.PROGRESSING) && !bender.getAbility().equals(NAME)) {
            return false;
        }
        return true;
}
```

**Comment by Koudja** [comment]
Résolu : 60a67c14e1998e53d5d137c7a05b11e51234f1b3
