### ISSUE TITLE
Arcs du Supply ramassables

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#112]
Bonjour !
Serait-il intéressant de supprimer automatiquement de l'inventaire les arcs donnés par le Supply des bows ? Ils ne devraient pas pouvoir être utilisés par d'autres personnes que les Bow, et lors d'évènements PVP comme le KOTH, on ramasse des tonnes d'arcs qui empêchent d'utiliser les sorts sur les slots où ils se placent.
J'ai bricolé ça pour DenyItem :

``` java
        if(bender == null || !bender.hasAffinity(BendingAffinity.BOW)) {
            if (item.getType() == Material.BOW) {
                ItemMeta bowmeta = item.getItemMeta();
                if (bowmeta.hasLore() && bowmeta.getLore().contains(Supply.BOW_LORE)) {
                    removeItem(bender.getPlayer(), item);
                }
            }
        }
```

Supply.BOW_LORE pourrait peut-être être une String plus caractéristique que "Bow", comme "Bow supplied" par exemple ?

**Comment by Koudja** [comment]
Bonne idée, merci : fbd54f397aabff98b26d9163182a791daffb7404
