### ISSUE TITLE
FireWall n'a pas de CD

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#113]
Bonjour !
Le FireWall peut se relancer immédiatement après sa disparition, la ligne `this.bender.cooldown(NAME, COOLDOWN);` n'est présente nulle part, alors que l'attribut cooldown existe bien.
EDIT : En fait c'est depuis très longtemps (my bad), donc c'est surement voulu.

**Comment by Koudja** [comment]
Pas nécessairement voulu, mais trop ancré pour faire une correction, il vaut mieux passer par le forum en guise de suggestion.
