### ISSUE TITLE
Fire : scoreboard toujours actif après changement de bending

### ISSUE THREAD

**Issue by Super-Thomate** [Avatar-Realms/spigot-bending#114]
Après un changement de bending, le nombre de point d'énergie disponible reste affiché lorsqu'on change de bending. Les cooldowns des autres éléments s'affichent correctement mais le Fire ne disparaît pas.
Un /b cd hide suivit de /b cd show fait disparaître le Fire.

**Comment by Koudja** [comment]
Résolu : 9508a2de1935673f69a3b89b0584260bc7da53e8
