### ISSUE TITLE
[Earth] Bug du passif

### ISSUE THREAD

**Issue by Desirtouan** [Avatar-Realms/spigot-bending#115]
Bonsoir !
Nous avons constaté ce soir avec Alfredalot le retour d'un ancien bug de la maîtrise de la terre. ^^'
Lorsque notre passif s'active, après une chute donc, le sable qui est censé disparaître au bout de quelques secondes reste en place et ce indéfiniment (d'après ce que nous avons pu observer jusqu'à maintenant).
Bonne soirée à vous, Desirtouan.

**Comment by Koudja** [comment]
Résolu: 45c4e5eefdea52b465d1b6331e305ed97123b24c
