### ISSUE TITLE
[Fire] : Lightning, fontaine de Jouvence

### ISSUE THREAD

**Issue by Super-Thomate** [Avatar-Realms/spigot-bending#116]
Tirer un lightning tout en tenant un seau de lait dans la main "rajeunit" une entité visée (si celle-ci dispose d'une forme "enfant").

**Comment by Super-Thomate** [comment]
Il semblerait, après une recherche plus approfondie, que faire des dégâts sur un animal ou pnj avec un seau de lait le fait consommer par la créature est le transforme en "enfant" (que ce soit un coup de poing, un AirSwipe ou même un FireBurst). Si plusieurs créatures sont touchées par l'attaque, une seule sera transformée (il semblerait que ce soit la première touchée #Logique).
Cela ne serait donc pas un bug bending mais une fonctionnalité étrange apportée par un plugin. En effet, en solo ou serveur sans plugin cela ne fonctionne pas, en revanche sur un serveur avec Essentials, cela fonctionne; il semblerait donc que cela vienne d'Essentials.

**Comment by Koudja** [comment]
Je clos le ticket alors (même si il faut réparer ça, cela ne vient pas du bending).
