### ISSUE TITLE
Poisonned dart - Multiple effect

### ISSUE THREAD

**Issue by Shuboh** [Avatar-Realms/spigot-bending#118]
J'ai remarquer que les autres forme du poisonned dart ne fonctionnait pas ^^ cela viens peut etre du fais qu'il n'y a pas marquer PotionEffectType. devant les effets nan ?(j'en ai en vraie aucune idée j'ai a peine commencer le code :/)

**Comment by Koudja** [comment]
Résolu : f5fc64caea7fd971d644f7dc1a26c1ee1a6b6e47
