### ISSUE TITLE
Surge n°2

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#12]
Bonjour !
Un second petit problème sur le Surge, on ne peut pas faire le WaterWall avec une fiole d'eau.
J'ai remarqué que dans la fonction prepare() de WaterWall.java, il n'y avait pas le cas
if(WaterReturn.hasWaterBottle(player)) qui est présent pour les autres sorts.

**Comment by Koudja** [comment]
C'est voulu tant niveau gameplay (pour favoriser les drainbend) que RP (quantité d'eau).
