### ISSUE TITLE
Heatcontrol Son²

### ISSUE THREAD

**Issue by Shuboh** [Avatar-Realms/spigot-bending#121]
Le heatcontrol fais un son tres dérangeant.

**Comment by Koudja** [comment]
J'apprécierais de ne pas réouvrir des tickets sur lesquels j'ai déjà répondu : le son ne s'active qu'une seule fois, indiquant le succès de la compétence, ce n'est pas réellement désagréable.

**Comment by Shuboh** [comment]
sans etre mechant ou paraitre insolent mais le son est toujours present, quand il y rien

**Comment by Shiryu75** [comment]
+1

le son se produit X fois alors qu'il n'y a pas matière à.
Et même sans présence de source de feu à éteindre, le son se produit ^^
