### ISSUE TITLE
Earthgrab: ne fonctionne plus 

### ISSUE THREAD

**Issue by Kingkopop** [Avatar-Realms/spigot-bending#127]
le Earthgrab ne fonctionne plus ne lance pas les cooldown et ne fait absolument rien comme si il était         désactivé.

**Comment by ghost** [comment]
Bonjour !
L'EarthGrab ne fonctionne plus à cause des éléments suivants :
- Le premier test de la méthode swing() devrait être `if (!isState(BendingAbilityState.START))`.
- Dans la méthode affect(Entity entity), this.target est appelé alors qu'il n'est jamais affecté.  Auparavant un `this.target = (LivingEntity) entity;` était utilisé.
- Dans la méthode sneak() (pour s'auto-grab), le test `if (this.target != null && affect(player))` est toujours faux, car this.target n'est jamais initialisé auparavant. Peut être un simple `if (affect(player))` suffirait dans ce cas ?

En espérant que ça puisse aider ! :)
