### ISSUE TITLE
Surge n°3

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#13]
Bonjour !
Un autre bug sur l'utilisation de la Wave cette fois. 
**1)** Lorsque l'on sneak pour choisir une source, puis que l'on sneak à nouveau pour la placer autre part sans avoir lancé la Wave, la balise ne se replace pas et la première est enlevée.
**2)** De plus, la prochaine Wave ne se lancera pas.

Dans la fonction sneak() de WaterWall.java, je pense qu'il y a plusieurs choses à rajouter dans le cas où la vague a déjà été préparée mais qu'on veut la préparer à nouveau, un peu comme ceci :  

``` java
[...]
else if (getState() == BendingAbilityState.PREPARED)
        {
            if (wave == null)
            {
                moveWater(); // Build wall
                setState(BendingAbilityState.PROGRESSING);
            }
            else
            {
                wave.remove(); // Pour corriger 2)
                remove();
                /* Pour Corriger 1) */
                if (bender.isOnCooldown(NAME))
                {
                    return false;
                }
                wave = new Wave(player);
                if (wave.prepare())
                {
                    setState(BendingAbilityState.PREPARED);
                }
            }
        }
[...]
```

J'espère que ça vous aidera !

**Comment by Koudja** [comment]
Problème résolu pour le 2). Le 1) ne pose pas réellement de problème (ouvrez un autre ticket si c'est le cas).
