### ISSUE TITLE
Earthblast passe au travers des block

### ISSUE THREAD

**Issue by Slyteer** [Avatar-Realms/spigot-bending#137]
Le earthblast passe au travers des block bendable
Exemple : je monte un mur je sélectionne un blast d'un côté et clic de l'autre côté du mur le blast vas traversé le mur
marche sur les autre structure autre que le raiseearth comme une petite montagne

![2017-05-14_19 11 06](https://cloud.githubusercontent.com/assets/17968821/26036184/5b6afcba-38d9-11e7-84ea-468d11661ee4.png)
![2017-05-14_19 11 19](https://cloud.githubusercontent.com/assets/17968821/26036239/1982e49c-38da-11e7-98b8-a83eef92b0fd.png)

![2017-05-14_19 11 26](https://cloud.githubusercontent.com/assets/17968821/26036185/5b6b7bb8-38d9-11e7-8f15-e9b754c343ae.png)

**Comment by Slyteer** [comment]
On peut toucher quelqu'un au travers avec l'aide a la visé

**Comment by Koudja** [comment]
C'est voulu pour rendre le maniement du blast possible.
