### ISSUE TITLE
[Earth Metal] Earthblast qui OneShot

### ISSUE THREAD

**Issue by Vodry** [Avatar-Realms/spigot-bending#142]
Coucou,

Il y a un petit bug avec le earthblast qui permet de sélectionner un barreau de fer, puis de passer cette source de fer sur des blocs bendables (terre par exemple). Au bout de plusieurs resélections sur ces blocks bendables, le blast va tout simplement OneShot l'ennemi.

Ce bug impacte peu le gameplay du bending, je pense donc qu'il n'est que secondaire de le fix. Néanmoins, je tenais à le signaler.

Cordialement,
Incry.

**Comment by Koudja** [comment]
Corrigé
