### ISSUE TITLE
AirSpout

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#15]
Bonjour ! :)
Aujourd'hui j'ai essayé de trouver la cause d'un vieux problème du Airspout : Quand on monte en AirSpout et qu'on rencontre une dalle posée dans la partie haute d'un bloc, l'Airspout se désactive. Ce bug est embêtant lorsque l'on build en hauteur, à proximité de dalles.
J'ai remarqué qu'une condition pour que l'AirSpout s'arrête était que la tête du joueur se trouve dans un bloc solide :

``` java
public boolean canTick() {
        [...]
        if (this.player.getEyeLocation().getBlock().isLiquid() 
                || BlockTools.isSolid(this.player.getEyeLocation().getBlock())) {
            return false;
        }
        return true;
}
```

Dans BlockTools.java :

``` java
public static boolean isSolid(Block block) {
        if (nonOpaque.contains(block.getType())) {
            return false;
        }
        return true;
    }
```

Du coup, les dalles sont considérées comme "solides", ce qui est normal, mais ne faudrait-il pas ajouter une condition dans la fonction canTick() pour gérer ce cas un peu spécial ? :)

**Comment by ghost** [comment]
Bonsoir !
Des joueurs m'ont rappelé qu'il n'y avait pas que les dalles qui étaient concernées. Et après des tests, la totalité des objets qui ne prennent pas tout le volume d'un bloc sont concernés (trappes, vitres etc ...).
Du coup, dois-je faire une liste, ou essayer d'implémenter quelque chose moi-même pour vous éviter une perte de temps ?

**Comment by Nokorbis** [comment]
C'est comme tu veux, faudra bien que quelqu'un le fasse un jour de toute façon.
