### ISSUE TITLE
Shockwave

### ISSUE THREAD

**Issue by Desirtouan** [Avatar-Realms/spigot-bending#2]
Bonsoir Noko et Koudja,
Voici donc le premier rapport concernant la maîtrise de la Terre. En espérant qu'il y en ait d'autres afin de résoudre le maximum de bugs possibles ! :blush:

Après l'utilisation du shockwave, deux constatations s'offrent à moi : l'incapacité de pouvoir earthblast et aussi l'incapacité d'utiliser l'eartharmor, tout cela dans la zone où le shockwave a touché des blocs.
Je n'ai pas repéré d'autres problèmes concernant ce sort.

Bonne soirée à vous !

**Comment by ghost** [comment]
Bonsoir !
Euuuuu, après quelques tests aujourd'hui avec un des derniers commit, ce bug a été corrigé par hasard xD
Après un shockwave, on peut bend les blocks et s'ajouter une earthamor avec ;)

**Comment by Nokorbis** [comment]
Bending 6.1 -> les blocs peuvent être sélectionnés mais ne peuvent pas être utilisés/envoyés

**Comment by ghost** [comment]
Sur le shockwave ? Un earthBlast par exemple ne marche pas ? Ca marchait pour moi ...
Par contre oui, sur un raiseEarth ca marche pas, mais tout marchait au niveau du shockwave il me semble :) (et comme cette issue ne concernait que le shockwave j'avais signalé que ça marchait x) )
