### ISSUE TITLE
RaiseEarth

### ISSUE THREAD

**Issue by Drae78** [Avatar-Realms/spigot-bending#21]
RaiseEarth : Colonnes bendables, mais dépop du bloc directement + si on saute de quelques blocs de hauteur sur un raiseearth, presque la moitié du raiseearth dépop

**Comment by Koudja** [comment]
ShockWave parfaitement disponible et fonctionnel.

**Comment by Drae78** [comment]
Quand j'essaye de bind le sort, ça me dit : "You do not have the permission to bind this ability"
EDIT : 
Fallait juste que j'aille reprendre le sort dans le temple

**Comment by Koudja** [comment]
Merci de ne pas éditer pour rajouter des bugs
