### ISSUE TITLE
FireBending

### ISSUE THREAD

**Issue by Drae78** [Avatar-Realms/spigot-bending#23]
FireBlade : Dès que l'on tape avec l'épée, elle dépop (Clic droit ou clic gauche)
HeatControl : Ne fonctionne pas pour marcher dans le feu
EDIT : 
Illumination : Quand le sort est actif, si on se place sur un escalier, drop des torches à l'infini (si on part de l'escalier ça s'arrête)

**Comment by Nokorbis** [comment]
Concernant le FireWall, il va falloir que vous le débloquiez vous-même (ou que vous attendiez que l'on migre les sorts débloqués)

**Comment by Rossmall** [comment]
Pour la Fireblade, on pourrait faire un test dans [BendingDenyItem.java](https://github.com/Avatar-Realms/spigot-bending/blob/master/src/main/java/net/avatar/realms/spigot/bending/listeners/BendingDenyItem.java) pour regarder si c'est le bender est fire ?
````java
// Swordman might keep extra shield & iron sword
		if(bender == null || !bender.hasAffinity(BendingAffinity.SWORD)) {
			if(item.getType() == Material.IRON_SWORD) {
				//FireBender might keep FireBlade
				if(!isFireBlade(item) || !bender.isBender(BendingElement.FIRE))
					bender.getPlayer().getInventory().remove(item);
			}
			if(item.getType() == Material.SHIELD {
				bender.getPlayer().getInventory().remove(item);
			}
		}
````
