### ISSUE TITLE
ChiBlocker - passif

### ISSUE THREAD

**Issue by Drae78** [Avatar-Realms/spigot-bending#25]
Dégâts de chute : Actifs

PS : Je trouve pas pour mettre les labels, désolé ^^'

**Comment by Koudja** [comment]
Fonctionne très bien de mon côté, en tant que joueur

**Comment by Les4** [comment]
Le passif qui ne nous faisait pas prendre de dégâts de chute n'est plus. Est-ce voulu ?

**Comment by Koudja** [comment]
Si ce n'est pas une blague, merci de relire ma réponse.

**Comment by Koudja** [comment]
Voir #63 pour la résolution
