### ISSUE TITLE
Double dégats Airswipe

### ISSUE THREAD

**Issue by Templarum** [Avatar-Realms/spigot-bending#26]
Si on prends un tic de dégats air swipe, qu'avec le knockback on recule légèrement, on peut reprendre les dégats directement après (1 swipe, 2 x dégats)

**Comment by Nokorbis** [comment]
@Koudja Cela vient du fait qu'avant le LivingEntity.damageEntity() ne pouvait faire qu'une fois par tick des dégâts, maintenant, comme tu gères les dégâts toi-même, les dégâts ne sont pas "contrôlés"

**Comment by Koudja** [comment]
Corrigé
