### ISSUE TITLE
Airscooter

### ISSUE THREAD

**Issue by Nicom75** [Avatar-Realms/spigot-bending#3]
Bonjour Koudja et Noko,

Ce n'est pas vraiment un bug mais plutôt une amélioration du airscooter que je propose ici, pour remettre une fonctionnalité qui était présente avant la mise à jour : le fait de pouvoir changer de slot sur un airscooter sans l'arrêter (bien sûr il doit se couper dès que l'on lance un autre sort).

J'ai repérer dans votre code la fonction "canTick()" de la classe "Airscooter" et d'après le commentaire que j'y est trouvé ligne 92 je pense que c'est ici qu'il faut modifier le code pour réaliser cette amélioration :

``` java
// TODO: Remove Scooter when using another ability instead of this
```

J'ai beaucoup apprécié le fait que vous nous ayez autorisé à accéder au code du serveur, je connais un peu Java mais pas du tout son utilisation associée à Minecraft, donc merci j'apprends beaucoup en regardant votre travail :)

J'ai ainsi essayé de comprendre comment marche le bending, et je vous propose donc une ébauche de code qui pourrait peut être correspondre à la fonctionnalité dont il est ici question en remplacement de la fonction "canTick()" de la classe "Airscooter" :

``` java
@Override
public boolean canTick() {
    if(!super.canTick() 
            || this.player.isSneaking() 
            || !this.player.isFlying()) {
        return false;
    }
    //Remove Scooter when using another ability
    Map<Integer, BendingAbilities> abilities = this.bender.getAbilities();
    for (BendingAbilities ba : abilities.values()){
        if(ba != AbilityManager.getManager().getAbilityType(this) && AbilityManager.getManager().isUsingAbility(player, ba))
            return false;
    }
    return true;
}
```

J'ai certainement fais des erreurs et suis peut être carrément à côté de la plaque lol, je sais qu'il est malheureusement plus facile d'ajouter des bugs que des fonctionnalités mais en tout cas j'aurai au moins essayé :D

En tout cas merci pour votre travail sur le serveur ! (surtout pour le système des voies que je trouve très original, je ne m'y attendais pas du tout lors de la mise à jour) 

Bonne soirée à vous.

Nicom75

**Comment by Nokorbis** [comment]
L'idée est pas mauvaise, c'est à analyser.

Merci de la proposition
