### ISSUE TITLE
Bloodbending #1

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#39]
Le cooldown du sort s'active au début de l'exécution du Bloodbending, et pas à la fin. Du coup, si on Bloodbend quelque chose pendant 5 secondes ou plus, on peut desneak+sneak pour reblood immédiatement. En gros, on peut blood à l'infini.

**Comment by ghost** [comment]
Hello ! :)
Bon c'est à ma portée ce bug x)
Je pense qu'il suffirait juste d'enlever, ligne 101 de BloodBending.java

``` java
BendingPlayer.getBendingPlayer(this.player).cooldown(this, COOLDOWN);
```

et de placer dans la methode remove()

``` java
this.bender.cooldown(NAME, COOLDOWN);
```
