### ISSUE TITLE
Icespike #1

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#41]
Disparition de la version "clic" du Icepike, c'est à dire de la version faisant émerger une colonne de glace à partir d'une source de glace (sol de glace), infligeant 1 coeur à la cible (entité).

**Comment by Koudja** [comment]
Fix 0c429988f0caa110039f3d310c9814a6730c6406 (et maintenant il est possible de IceSpike sur autre que de la glace)
