### ISSUE TITLE
Surge glacé - Impossibilité de l'enlever et permanence des blocs

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#44]
Quand on glace une surge (sneak sur une entité), on ne peut plus l'enlever avec un autre sneak. De plus, si on reste à côté de la Surge trop longtemps par exemple, celle ci devient permanente et les blocs de glace ne s'enlèvent pas. Le seul moyen d'enlever la glace d'une Surge est de sortir du rayon de lancé (environ 20 blocs).

**Comment by Rossmall** [comment]
Hello ! :)
J'ai essayé de corriger ce bug là aussi, mes propositions sont présentes dans le pull request sur le Surge :) Après je ne sais pas si c'est très joli ce que j'ai fais, à vous de voir :)

**Comment by Koudja** [comment]
Après plusieurs test, ce bug semble être résolu. Je le clos, mais n'hésitez pas à le ré-ouvrir si ce n'est pas le cas (avec une procédure pour reproduire le problème).
