### ISSUE TITLE
Surge glacé - Impossibilité de bend pendant

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#45]
Quand une Surge gelée est faîtes, on ne peut plus bend tant que celle ci est encore là. En gros, si on sort pas du rayon de lancé, on peut plus utiliser les fioles, et on ne peux plus utiliser le sort de Surge.

**Comment by Koudja** [comment]
Après plusieurs test, ce bug semble être résolu. Je le clos, mais n'hésitez pas à le ré-ouvrir si ce n'est pas le cas (avec une procédure pour reproduire le problème).
