### ISSUE TITLE
Torrent #1

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#46]
La glace des Torrent ne reste plus au sol comme avant, à part si on reste en sneak. Avant on pouvait exécuter ce sort plusieurs fois, et la glace pouvait se faire Heatcontrol (contrairement à maintenant). De plus, une bulle d'air est censée se créer au niveau de la tête des entités prises au piège. Cela ne semble pas fonctionner parfaitement.

**Comment by Koudja** [comment]
Fait :  e1cf99a
