### ISSUE TITLE
Torrent - Duplication au lancement

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#47]
De temps en temps, les Torrent se "dédoublent". En gros, une sorte de deuxième Torrent s'active autour de nous quand on a placé la glace de ce dernier. Cela peut engendrer une nouvelle boule de glace, ou juste un bug graphique. Cela se passe pendant 1 seconde, puis le "nouveau" Torrent disparaît.

**Comment by Koudja** [comment]
Impossibilité à reproduire, je suppose que le bug a été résolu par un précédant commit. Si ce n'est pas le cas, merci de ré-ouvrir ce ticket.
