### ISSUE TITLE
AirSuction

### ISSUE THREAD

**Issue by Nicom75** [Avatar-Realms/spigot-bending#5]
Re-bonsoir,

Promis c'est mon dernier message avant longtemps, je vous embête plus après :p

Lorsque l'on tire un AirSuction (le swing, pas le sneak) une balise se pose comme si l'on avait fait un sneak. Seul un second tire lance le suction.

Si je ne me trompe pas ça vient d'un problème de "state" dans la classe "Suction" : à la ligne 112 dans la méthode "swing()", un suction qui vient d'être créé et qui est donc dans l'état "start" passe à l'état "preparing" puis la fonction s'arrête. Voici le code en question :

``` java
public class AirSuction extends BendingActiveAbility {
    [...]
    @Override
    public boolean swing() {
        if (getState() == BendingAbilityState.Start) {
            this.origin = this.player.getEyeLocation();
            setState(BendingAbilityState.Preparing);
            return false;
        } else if (getState() == BendingAbilityState.Preparing) {
            [...]
        }
    }
    [...]
}
```

Je pense qu'il faudrait faire comme dans la classe "Airblast", et faire en sorte que la fonction ne s'arrête pas, pour que la prochaine condition s'éxecute. Voici le code tiré de la méthode "swing()" de la classe "Airblast" :

``` java
public class AirBlast extends BendingActiveAbility {
    [...]
    @Override
    public boolean swing() {
        if(getState() == BendingAbilityState.Start) {
            this.origin = this.player.getEyeLocation();
            setState(BendingAbilityState.Preparing);
        }
        //It is NORMAL that both if could follow in same click
        if(getState() == BendingAbilityState.Preparing) {
            [...]
        }
    }
    [...]
}
```

Merci et encore bonne soirée :D

Nicom75

**Comment by Nokorbis** [comment]
>  Promis c'est mon dernier message avant longtemps, je vous embête plus après :p  

Tu sais, tu fais autant de bug report que tu veux x)
