### ISSUE TITLE
WaterSpout infini

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#53]
Le WaterSpout ne se coupe jamais, sauf s'il rencontre un bloc différent d'un bloc bendable. Avec une poussée par le dessous, on peut donc utiliser son WaterSpout dans les airs, sans eau directement sous ses pieds.

**Comment by Koudja** [comment]
Cela a du être corrigé avec : f3d61cdb6f62cbccb74ca7417deab9f1b995640f
