### ISSUE TITLE
Suffocate?Annulation des dégats du AirSwipe ?

### ISSUE THREAD

**Issue by Ropse** [Avatar-Realms/spigot-bending#55]
Bonjour/Bonsoir,

Je fait ce post pour signaler un bug de la maitrise de l'Air (sans blague).

Après avoir fait du PvP en arène je me suis rendu compte qu'après avoir utilisé le Suffocate, mes AirSwipes ne faisait plus aucun dégats (il passait à travers mon adversaire). j'ai donc fait plusieurs tests contre des Earths,Fire,ChiB et Air, le suffocate après utilisation annule les dégats des AirSwipes !

**Comment by Koudja** [comment]
Lorsqu'un joueur se prend des dégâts d'une autre entités, il y a une invulnérabilité de 10 ticks (soit 500ms). Le suffocate est réglé pour blesser toutes les secondes, donc rendant sa cible invulnérable la moitié du temps.
