### ISSUE TITLE
Bloodbending  #2

### ISSUE THREAD

**Issue by Riqoulouru** [Avatar-Realms/spigot-bending#58]
Clic gauche sur le slot du bloodbend déclenche le cooldown

**Comment by ghost** [comment]
Bonjour !
Je pense qu'il suffirait de tester si le Blood est lancé dans la méthode swing non ? Pour aboutir à quelque chose du genre :

``` java
public boolean swing() {
        if (getState() == BendingAbilityState.PROGRESSING) {
            [...] //Fonction actuelle
        }
        return false;
    }
```
