### ISSUE TITLE
Field access exeption eartharmor

### ISSUE THREAD

**Issue by kikipunk** [Avatar-Realms/spigot-bending#61]
quand on veux lancé une EarthArmor avec clic gauche (fonctionne pas plus erreur)
Les log:

> [07:30:11] [Server thread/ERROR]: Could not pass event PlayerAnimationEvent to Bending v6.1.0
> org.bukkit.event.EventException
>   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1385) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.PacketPlayInArmAnimation.a(SourceFile:32) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.PacketPlayInArmAnimation.a(SourceFile:9) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_25]
>   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0_25]
>   at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0_25]
>   at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   at java.lang.Thread.run(Thread.java:724) [?:1.7.0_25]
> Caused by: java.lang.IllegalAccessError: tried to access field net.avatar.realms.spigot.bending.abilities.BendingAbility.register from class net.avatar.realms.spigot.bending.abilities.earth.EarthArmor
>   at net.avatar.realms.spigot.bending.abilities.earth.EarthArmor.moveBlocks(EarthArmor.java:169) ~[?:?]
>   at net.avatar.realms.spigot.bending.abilities.earth.EarthArmor.swing(EarthArmor.java:74) ~[?:?]
>   at net.avatar.realms.spigot.bending.listeners.BendingPlayerListener.onPlayerSwing(BendingPlayerListener.java:256) ~[?:?]
>   at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source) ~[?:?]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_25]
>   at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_25]
>   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-b1c1b55-7d73fbb]
>   ... 16 more

**Comment by Koudja** [comment]
Heu, nope :o, vérifie que ton repo local est bien à jour (et pas avec un conflit en cours)
