### ISSUE TITLE
Maitre d'art

### ISSUE THREAD

**Issue by Cocopops1** [Avatar-Realms/spigot-bending#63]
Les Maitres d'art ont des dégats de chute

**Comment by ghost** [comment]
Hello !
Je pense que le problème est identique à #25. J'ai remarqué que dans BendingPlayerListener ligne 414, le test `EntityTools.canBendPassive(player, BendingElement.MASTER))` renvoyait faux en toutes circonstances. 
Et en l'occurrence, dans canBendPassive, c'est le test 
`(!player.hasPermission("bending." + element.name() + ".passive"))` qui est vrai. Ne serai-ce pas un problème de permissions du coup ?

**Comment by Cocopops1** [comment]
perso j'ai encore des dégats de chute 
![1](https://cloud.githubusercontent.com/assets/18104714/14826217/672e6108-0bcc-11e6-96cf-2721d1bd2607.png)->
![2](https://cloud.githubusercontent.com/assets/18104714/14826229/6f03daca-0bcc-11e6-9e6c-53244d028005.png)->
![3](https://cloud.githubusercontent.com/assets/18104714/14826239/74a5c268-0bcc-11e6-956c-a34104eaa425.png)

**Comment by ghost** [comment]
Hello ! :)
Oui le problème est toujours d'actualité, ce post n'a pas été fermé, c'est simplement le "doublon" #25 qui a été fermé, ce pourquoi tu as du être notifié :)

**Comment by Koudja** [comment]
C'est bien un problème de permissions, et non du code.
