### ISSUE TITLE
Fire - Illumination

### ISSUE THREAD

**Issue by JohannaDD** [Avatar-Realms/spigot-bending#67]
Bonjour,

Lorsque nous faisons illumination, une torche se drop dans notre slot/inventaire. Plus aucune torche ne nous suit.
Le problème est que si nous sommes hors de nos claims ou hors du wilderness, ces torches ne peuvent être posées et donc sont inutiles. De plus le heatcontrol nous permet déjà de créer des torches.

Merci

**Comment by JohannaDD** [comment]
Up
L'illumination est vraiment une catastrophe telle qu'elle est actuellement. Si il y a possibilité d'au moins le remettre comme avant

**Comment by Koudja** [comment]
Fait : adf5522f73b1b60f00cd5deb72e57a60b87d9be5
