### ISSUE TITLE
Feu - Dégats combustion

### ISSUE THREAD

**Issue by JohannaDD** [Avatar-Realms/spigot-bending#68]
Bonjour,

Le combustion ne fait des dégats qu'une fois sur trois sur les mobs/joueurs. Le knockback est tout le temps présent ainsi que la destruction. Seuls les dégats sont aléatoires.

Merci

**Comment by Koudja** [comment]
L'aire d'effet des dégâts était volontairement inférieur à celui pour la repousse. Vu que cela gêne, ils ont été ajusté pour être égaux (ajustement par le haut).
