### ISSUE TITLE
Bug Ellytra

### ISSUE THREAD

**Issue by Templarum** [Avatar-Realms/spigot-bending#69]
Il est possible pour un non AirBender d'équiper des Ellytras en passant par un dispenser, (en mettant les ellytras dedans, en se positionnant devant, et en l'activant).

Merci

**Comment by ghost** [comment]
Salut ! :)
Je n'ai pas trouvé de moyen de capter un item reçu directement sur un slot de l'armure :/ Du coup, il faudrait peut être faire un EventHandler en plus dans BlockDenyItem.java pour éviter que les dispensers n'envoient des Elytras ?

``` java
@EventHandler
    public void onBlockDispenseEvent(BlockDispenseEvent event) {
        if(event.getItem().getType() == Material.ELYTRA) {
            event.setCancelled(true);
        }
    }
```

Ah et autre chose, il y a aussi un problème lorsqu'un joueur ramasse des Elytras sur le slot qu'il a déjà séléctionné : Elles ne s'enlèvent pas, il peut donc les équiper. Je cherche encore pour ce problème là ^^

**Comment by Koudja** [comment]
J'ai ajouté un garde-fou qui check l'équipement périodiquement des joueurs. Cela devrait couvrir les éventuels autre cas où le plugin ne peux récupérer les évènements.
