### ISSUE TITLE
Air Slice

### ISSUE THREAD

**Issue by Templarum** [Avatar-Realms/spigot-bending#70]
Les balises de l'AirSlice reste en place lorsque l'on change de slot, tant que l'une de nos balises est présente:
Il est impossible de lancer un airswipe via clic souris ( L'air swipe sneak fonctionne)
Il est impossible de lancer un airscooter

**Comment by ghost** [comment]
Bonjour !
On faudrait peut-être rajouter une fonction canTick() pour l'AirSlice de cette forme ?

``` java
@Override
    public boolean canTick() {
        if(!super.canTick()) {
            return false;
        }
        if (getState() == BendingAbilityState.PREPARING && !NAME.equals(bender.getAbility())) {
            return false;
        }
        return true;
    }
```

**Comment by ghost** [comment]
Bonjour ! Ce bug était bien résolu [suite à la publication du 20 Juillet](https://bendercraft.net/viewtopic.php?f=45&t=336), mais est de nouveau présent aujourd'hui. L'AirSlice ne s'annule donc plus en changeant de slot

**Comment by ghost** [comment]
Bonjour !
Bon en fait, l'AirSlice se désactive bien quand une balise est posée et que l'on change de slot, mais pas quand les deux balises sont posées. Peut être faut-il changer la deuxième condition de la fonction cantick() en

``` java
if (!getState().equals(BendingAbilityState.PROGRESSING) && !NAME.equals(bender.getAbility())) {
            return false;
}
```
