### ISSUE TITLE
Metalbending : hook

### ISSUE THREAD

**Issue by Slyteer** [Avatar-Realms/spigot-bending#71]
On peut ce propulser en arrière en mettant sont grappin sur soit même. même quand on ne touche pas le sol

**Comment by Koudja** [comment]
Es tu sûr que ça marche aussi lorsque tu ne touches pas le sol ? Et lorsque tu dis "ne touches pas le sol" tu veux dire vraiment en l'air ou juste en train de sauter (i.e. à 1 bloc du sol) ?
