### ISSUE TITLE
Pomme dorée et AvatarWildLife

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#73]
Bonsoir !
On ne peut plus se saisir de pommes dorées, du coup plus de lémurien :/ On pourrait peut-être les laisser dans l'inventaire mais empêcher leur consommation ?
Il faudrait les retirer de BendingDenyItem.java ligne 191, et ajouter le handler suivant :

``` java
@EventHandler
    public void onPlayerItemConsumeEvent(PlayerItemConsumeEvent event) {
        if(event.getItem().getType() == Material.GOLDEN_APPLE) {
            event.setCancelled(true);
        }
    }
```

**Comment by Koudja** [comment]
Utilisation des pommes normales.
