### ISSUE TITLE
Lavabending : obsidian non bendable

### ISSUE THREAD

**Issue by kikipunk** [Avatar-Realms/spigot-bending#79]
bonjour,
L'obsidian devrait être bendable pour le raiseearth et le lavatrain comme codé:

```
        if (EntityTools.isSpecialized(player, BendingAffinity.LAVA) 
                && (block.getType() == Material.OBSIDIAN) 
                && ((ability.equals(EarthWall.NAME)) || (ability.equals(LavaTrain.NAME)))) {
            return true;
        }
```

mais cela ne fonctionne pas. Pour le lavatrain cela déclanche quand même le cooldown.

Merci

**Comment by kikipunk** [comment]
Edit:
(ability.equals(EarthWall.NAME)) ne renvois a rien, je m'explique

Si l'on retire l'ability.equals tous fonctionne, l'obsidian est bendable par les lava.

Si l'on mes 
`System.out.print(ability.getAbility());`
dans le if, le serveur renvoie bien 

> [11:25:28 INFO]: class net.avatar.realms.spigot.bending.abilities.earth.EarthWall

Le problème viens de la le 
`ability.equals(LavaTrain.NAME)`
ne s'execute jamais

j'espère avoir  été clair.

Merci

**Comment by ghost** [comment]
Salut ! :)
Le problème c'est pas qu'il faut utiliser ability.getName().equals() au lieu de ability.equals() ? :)

**Comment by kikipunk** [comment]
C'est for possible mais j'ai fait un pull request avec des petite modifications dans le gameplay (donc pour l'instant j'essaye pas) 
Mais grand merci pour cette probable bonne solution.

**Comment by Koudja** [comment]
Fix: 2beac0a
