### ISSUE TITLE
Airburst

### ISSUE THREAD

**Issue by Nicom75** [Avatar-Realms/spigot-bending#8]
Bonjour,

Tout d'abord encore merci pour la correction des autres bugs :)

Le AirBurst pose encore un petit souci, cette fois-ci à propos de son chargement et de son état "preparing". 

3 cas de figure lorsque l'on sneak sur le slot du Airburst :
- Si on le charge complètement et qu'on veut le lancer : pas de soucis on relâche le sneak ou on clique et le sphereburst ou le coneburst se déclanche
- Si on le charge complètement et que l'on ne veut plus le lancer : big problème même en changeant de slot le chargement du burst est toujours là et le burst partira si l'on relâche le sneak (même sur un autre slot).
- Si le burst n'est pas encore chargé entièrement et que l'on change de slot : on peut utiliser les autres sorts, et si l'on revient sur le slot du burst et que l'on sneak il est déjà entièrement chargé et prêt à être lancé !

On a essayé de comprendre ce qui pourrait causer cela Rossmall et moi et nous pensons que cela vient peut être du fait que la classe Airburst n'a pas de méthode "canTick()" redéfinie (c'est donc la méthode "canTick()" de la classe mère qui est appelée). La méthode "canTick()" copiée de la classe du suction ci-dessous pourrait peut être faire l'affaire (changer de slot alors que le burst n'est pas encore lancé le supprime) :

``` java
@Override
public boolean canTick() {
    if(!super.canTick()) {
        return false;
    }
    if (!getState().equals(BendingAbilityState.Progressing) && (bender.getAbility() != BendingAbilities.AirBurst)) {
        return false;
    }
    return true;
}
```

Je pense que ce bug n'avait pas encore été reporté car le Airburst n'était plus trop utilisé, car beaucoup moins puissant qu'avant (Rossmall a d'ailleurs fais une suggestion sur le forum aujourd'hui pour proposer de réaugmenter sa puissance d'éjection).

Bonne soirée à vous.

Nicom75

**Comment by ghost** [comment]
Hello !
Du coup j'y pense, mais pour faire que le "chargement" revienne à zéro si l'on arrête de sneaker mais tout en restant sur le slot, il ne faudrait pas une condition en plus ? Ce qui donnerai : 

``` java
@Override
    public boolean canTick()
    {
        if(!super.canTick())
        {
            return false;
        }
        if(getState().equals(BendingAbilityState.Preparing) && !this.player.isSneaking())
        {
            return false;
        }
        if (!getState().equals(BendingAbilityState.Progressing) && (bender.getAbility() != BendingAbilities.AirBurst))
        {
            return false;
        }
        return true;
    }
```
