### ISSUE TITLE
ToggleAffinity pour Drainbend

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#82]
Hello !
Un simple problème, on ne peut pas toggle l'affinité Drainbend, du coup ça va peut-être être ennuyeux pour le probend non ?
Il faudrait tester si le joueur a toggle son affinité dans canDrainBend(), un peu comme cela :

``` java
public static boolean canDrainBend(Player player) {
        if (player == null) {
            return false;
        }

        BendingPlayer bender = BendingPlayer.getBendingPlayer(player);
        if (bender == null || !bender.hasAffinity(BendingAffinity.DRAIN) || EntityTools.getToggledAffinities().contains(player.getUniqueId())) {
            return false;
        }

        return true;
    }
```

Et il faudrait aussi changer EntityTools.java, canPlantBend() deviendrait :

``` java
public static boolean canPlantbend(Player player) {
        BendingPlayer bPlayer = BendingPlayer.getBendingPlayer(player);
        if (bPlayer == null) {
            return false;
        }
        if (EntityTools.isSpecialized(player, BendingAffinity.DRAIN) && !getToggledAffinities().contains(player.getUniqueId())) {
            return true;
        }
        return false;
    }
```

**Comment by Koudja** [comment]
Yop, merci : bde4aa6

Il existe une fonction renvoyant un booléen pour savoir si une affinité est active ou non, il est préférable de l'utiliser plutôt que de reproduire le fonctionnement.
Concernant le plantbend, il est préférable de juste le rediriger vers le drainbend, car ils faisaient le même check.

**Comment by ghost** [comment]
Ah je n'avais pas vu cette fonction ^^
Ok pour le plantbend, merci de m'avoir répondu ! :D
