### ISSUE TITLE
air : problème collision airswipe

### ISSUE THREAD

**Issue by Voltagen** [Avatar-Realms/spigot-bending#86]
Le airswipe traverse le fireburst sneak sans le stopper

**Comment by Koudja** [comment]
Cela a toujours été le cas et n'est donc pas un bug (utilisez le forum suggestion).

**Comment by ghost** [comment]
Bonjour ! Non justement, avant la BendingV6 on pouvait contrer une zone du FireBurst sphere avec un AirSwipe. Mais oui on va passer par les suggestions !
