### ISSUE TITLE
AirBubble/WaterBubble

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#9]
Bonjour !
Je voudrais suggérer une petite modification au niveau du AirBubble :) En ce moment, à chaque clic, l'airbubble s'active/se désactive, et donc casser un bloc sous l'eau revient à une succession d'activations/désactivations.
Ci dessous dans la fonction swing() de bubble.java, j'ai remarqué qu'à chaque appel, on fait appel à remove(), peut être est-ce la cause ?

``` java
@Override
    public boolean swing() {
        [...]
        remove();
        return false;
    }
```

On pourrait peut être revenir à l'ancien système, où la désactivation du bubble ne se faisait qu'en changeant de slot ?

Merci ! :)

**Comment by Nokorbis** [comment]
J'ai fait en sorte que les Bubbles puissent s'activer avec un outils en main mais ne se désactive pas si on a un outils en main et que l'on clique. Cela convient-il ?

**Comment by ghost** [comment]
Ah oui j'allais aussi faire un rapport pour l'activation avec outils, mais oui c'est très bien comme ça ! Merci :)
