### ISSUE TITLE
DenyItem pour les armures

### ISSUE THREAD

**Issue by ghost** [Avatar-Realms/spigot-bending#90]
Bonjour !
Un petit soucis lorsque l'on a un item interdit équipé sur un slot de l'armure :
Le 

``` java
for(ItemStack itemstack : player.getInventory().getArmorContents()) {
            sanitize(bender, itemstack);
        }
```

permet bien de détecter les items "illégaux", mais en revanche, l'appel à `bender.getPlayer().getInventory().remove(item);` ne permet pas de supprimer ces items si ils sont présent sur un des slots de l'armure.

**Comment by Koudja** [comment]
Fait : 02e34017dc0ae7077919fdd87508cbc1430691c4
