### ISSUE TITLE
Firebending : le Firejet annule les dégâts de chute

### ISSUE THREAD

**Issue by Helllios** [Avatar-Realms/spigot-bending#98]
Les Firebender ne prennent pas les dégâts de chute pendant leur cooldown de Firejet après un cast de ce sort.

**Comment by ghost** [comment]
Hello !
Bon j'ai réalisé quelques tests pour savoir à quoi c'était du. Vous le saviez peut être déjà mais c'est le fait de mettre le joueur en Fly dans FlyingPlayer qui fait que l'on a pas de dégâts de chute à la fin du Firejet.
C'est aussi pour cela que les Water n'ont pas de dégâts de chutes après un WaterSpout (ou rarement).

Bref, je ne vois pas trop comment changer cela ^^

**Comment by Shiryu75** [comment]
C'est normal que les firebenders ne prennent pas dégâts de chute. 
En contre partie de l'augmentation drastique du cooldown à 6 secondes, le fall damage a retiré. Le vrai bug ici c'est plutôt qu'on prenne des dégâts APRES la fin du cooldown d'ailleurs

**Comment by ghost** [comment]
Hummmmm, d'où tiens-tu tes sources ? T'as l'air d'être bien au courant quand même, comparé à la majeure partie de la communauté x)

**Comment by Shiryu75** [comment]
C'est peut-être pas le meilleur endroit pour en parler ^^

Nous avons vu apparaître plusieurs dizaines de posts forum concernant le firebending en général, sur bendercraft comme sur AR. On a bouffé je ne sais combien de nerfs suite aux railleries sur le firejet wallof. 
Mes sources ? C'est simplement mes 2 ans d'expérience exclusivement en tant que fire :)

**Comment by Koudja** [comment]
Résolu dans un commit à venir.
